// <auto-generated />
using System;
using DreamsSyncronizer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamsSyncronizer.Migrations
{
    [DbContext(typeof(SleepTrackerDbContext))]
    [Migration("20240521183016_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.Auth.UserDb", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LinkId")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("DbId");

                    b.HasIndex("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.Sync.SyncPartDb", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientDbVersion")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<string>("JsonData")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LinkId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DbId");

                    b.HasIndex("LinkId", "Key");

                    b.ToTable("SyncPartDbs");
                });

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.UserDeviceDb", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<int?>("UserDbDbId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DbId");

                    b.HasIndex("UserDbDbId");

                    b.ToTable("UserDeviceDbs");
                });

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.VersionApp", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Store")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("DbId");

                    b.ToTable("VersionApps");
                });

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.UserDeviceDb", b =>
                {
                    b.HasOne("DreamsSyncronizer.Models.Db.Auth.UserDb", "UserDb")
                        .WithMany("DeviceDbs")
                        .HasForeignKey("UserDbDbId");

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("DreamsSyncronizer.Models.Db.Auth.UserDb", b =>
                {
                    b.Navigation("DeviceDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
